Properly infer full_docs
3efe567b9ede ("Enhanced hover tooltips") added the `full_docs`
configuration option as an `Inferrable`. However, it failed to actually
merge the option during a config update, causing a panic if the client
specified `full_docs` to be `null`. Example panic:

    thread '<unnamed>' panicked at 'internal error: entered unreachable code', src/config.rs:111:33

Fix this to prevent the crash.