Mention zlib development headers as build dependency
Without this, the compilation of the openssl-sys crate fails on my
Debian testing machine:

     Compiling openssl-sys v0.9.10
  error: failed to run custom build command for `libssh2-sys v0.2.5`
  process didn't exit successfully: `/home/mg/src/rls/target/release/build/libssh2-sys-e917cad9dc0cbe58/build-script-build` (exit code: 101)
  --- stdout
  running: "cmake" "/home/mg/.cargo/registry/src/github.com-1ecc6299db9ec823/libssh2-sys-0.2.5/libssh2" "-DCRYPTO_BACKEND=OpenSSL" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB_COMPRESSION=ON" "-DCMAKE_INSTALL_LIBDIR=lib" "-DBUILD_EXAMPLES=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_INSTALL_PREFIX=/home/mg/src/rls/target/release/build/libssh2-sys-9cc98b1c475d5dff/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
  -- Configuring incomplete, errors occurred!
  See also "/home/mg/src/rls/target/release/build/libssh2-sys-9cc98b1c475d5dff/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  fatal: Not a git repository (or any parent up to mount point /home)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
    Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
    /usr/share/cmake-3.7/Modules/FindZLIB.cmake:114 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    src/CMakeLists.txt:239 (find_package)

The installation command for Fedora has not been tested, but the
package name is based on https://apps.fedoraproject.org/packages/zlib.